# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React app build, test and deploy(only main changes)CI/CD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
      - name: Run npm install
        run: npm ci
      - name: Run build
        run: npm run build --if-present
      - name: Install dependencies in packages/car-race
        run: npm ci --prefix packages/car-race
      - name: Run tests
        run: npm test --prefix packages/car-race
      - name: Upload npm debug log if it exists
        uses: actions/upload-artifact@v4
        if: failure() # Only upload on failure, or use always() to upload regardless
        with:
          name: npm-debug-log
          path: |
            /home/runner/.npm/_logs/*.log
          if-no-files-found: ignore # Optional: don't fail the step if the log isn't found
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
